name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false # run all matrix combinations even if some fail
      matrix:
        include:
          # - os: windows-latest
          #   c_compiler: cl
          #   cpp_compiler: cl
          #   build_type: MinSizeRel
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            build_type: MinSizeRel
            cxx_flags: "-Wall -Wextra -Wshadow -Wpedantic -Werror"
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
            build_type: MinSizeRel
            cxx_flags: "-Wall -Wextra -Wshadow -Wpedantic -Werror"

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags}}"
        -S ${{ github.workspace }}

    - name: Build
      # --config is needed for windows
      run: cmake --build ${{ steps.strings.outputs.build-dir }} --config ${{ matrix.build_type }}
